created stats module
shagalalab/qarejet-android pull request #31
Opened 2020-10-03 19:32 UTC by MambetniyazovAmir

2020-10-05 16:58 UTC, Khareken reviewed
Ok

2020-10-07 11:05 UTC, Khareken approved these changes

2020-10-07 11:10 UTC, atabekm requested changes

2020-10-07 11:10 UTC, atabekm commented on .idea/codeStyles/Project.xml
> +          <package name="io.ktor" withSubpackages="true" static="false" />
Do not need to change this file, usually it is changed if you change Android Studio settings. I pushed this file in order to have a unified coding style among all participants.

2020-10-07 11:10 UTC, atabekm commented on build.gradle
> +    }
This should have been added automatically by Android Studio, but we don't need it. We use `Dependencies.kt` to track versions.

2020-10-07 11:10 UTC, atabekm commented on feature-stats/src/main/AndroidManifest.xml
> +<manifest package="com.shagalalab.feature.mylibrary" />
Looks like it was not clear from my wiki, but here `mylibrary` was used as a placeholder, you need to use your feature name instead.

2020-10-10 11:00 UTC, MambetniyazovAmir commented on .idea/codeStyles/Project.xml
> +          <package name="io.ktor" withSubpackages="true" static="false" />
Should I add it to gitignore it in later commits? Or is there a way to make Android Studio settings so that this file will be the same.

2020-10-10 12:02 UTC, atabekm commented on .idea/codeStyles/Project.xml
> +          <package name="io.ktor" withSubpackages="true" static="false" />
No, do not add to gitignore. I think these are specific project level changes, i.e. not applicable to all Android Studio projects. My suggestion is, revert this change, then do not modify code style settings. If it is somehow interfering with other project settings, then the other option could be having a separate Android Studio instance only for ShaǵalaLab projects.

2020-10-11 10:44 UTC, atabekm commented on .idea/codeStyles/Project.xml
> +                  <XML_NAMESPACE>http://schemas.android.com/apk/res/android\n</XML_NAMESPACE>
Now you have these `\n`'s at the end in three places

2020-10-11 11:37 UTC, atabekm approved these changes

2020-10-11 13:45 UTC, Khareken approved these changes

2020-10-11 13:45 UTC, Khareken approved these changes

2020-10-11 13:46 UTC, Khareken approved these changes

2020-10-11 13:46 UTC, Khareken approved these changes

2020-10-11 13:46 UTC, Khareken approved these changes

2020-10-11 13:58 UTC, merged