Ernazar
shagalalab/qarejet-android pull request #33
Opened 2020-10-13 00:40 UTC by Khareken

added feature add transaction

2020-10-15 20:09 UTC, MaratKhakim requested changes

2020-10-15 20:09 UTC, MaratKhakim commented on build.gradle
> +    }
No need for this

2020-10-15 20:09 UTC, MaratKhakim commented on feature-addtransaction/src/main/AndroidManifest.xml
> +<manifest package="com.shagalalab.feature.mylibrary"/>
You need to use your feature name

2020-10-15 20:50 UTC, MaratKhakim requested changes

2020-10-15 20:50 UTC, MaratKhakim commented on build.gradle
> +        classpath "com.android.tools.build:gradle:4.1.0"
Please, don't change it

2020-10-15 20:50 UTC, MaratKhakim commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-bin.zip
Please, don't change it

2020-10-15 20:58 UTC, Khareken commented on build.gradle
> +        classpath "com.android.tools.build:gradle:4.1.0"
i only deleted

2020-10-15 20:58 UTC, Khareken commented on build.gradle
> +        classpath "com.android.tools.build:gradle:4.1.0"
ext {
        kotlin_version = '1.4.10'
    }

2020-10-17 05:25 UTC, atabekm requested changes

2020-10-17 05:25 UTC, atabekm commented on build.gradle
> +        classpath "com.android.tools.build:gradle:4.1.0"
Revert all changes in this file, they are not related to your task

2020-10-17 05:25 UTC, atabekm commented on feature-addtransaction/src/main/AndroidManifest.xml
> +<manifest package="com.shagalalab.feature.addtransaction"/>
Looks like you haven't read the ticket description carefully, as I've provided there a proper module name

2020-10-17 05:25 UTC, atabekm commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip
Revert all changes here

2020-10-17 05:25 UTC, atabekm commented on settings.gradle
> +include ':feature-addtransaction'
Wrong module name

2020-10-22 11:32 UTC, atabekm commented
Recreated as https://github.com/shagalalab/qarejet-android/pull/34, so closing this one

2020-10-22 11:32 UTC, closed without merging