Add RecordsFragment #10
shagalalab/qarejet-android pull request #35
Opened 2020-10-26 22:58 UTC by MaratKhakim

2020-10-29 21:17 UTC, Khareken approved these changes

2020-10-29 21:19 UTC, Khareken submitted a review, later dismissed

2020-10-29 22:55 UTC, atabekm requested changes
Overall looks good, I just put some minor improvement suggestions

2020-10-29 22:55 UTC, atabekm commented on app/src/main/res/navigation/bottom_nav_graph.xml
> +<?xml version="1.0" encoding="utf-8"?>
I think it would be better to name this graph as `main_nav_graph.xml`

2020-10-29 22:55 UTC, atabekm commented on app/src/main/java/com/shagalalab/qarejet/presentation/DashboardFragment.kt
> +class DashboardFragment : Fragment(R.layout.fragment_dashboard)
Since this is a temporary fragment, let's minimise the creation of temporary files. So, I suggest to get rid of `fragment_dashboard.xml`, and create fragment's layout programmatically. Just add one TextView, no need to center it. And if you want, you can give some background color to fragment from android's color resources, that should be it. This will allow us to just remove this file when we start working on real dashboard screen implementation.

2020-10-31 00:18 UTC, atabekm approved these changes

2020-10-31 01:21 UTC, Khareken approved these changes

2020-10-31 01:22 UTC, Khareken approved these changes

2020-10-31 01:30 UTC, merged