added empty statsFragment
shagalalab/qarejet-android pull request #36
Opened 2020-11-05 07:10 UTC by MambetniyazovAmir

2020-11-05 20:11 UTC, MaratKhakim requested changes

2020-11-05 20:11 UTC, MaratKhakim commented on feature-stats/src/main/java/com/example/feature/stats/presentation/StatsFragment.kt
> +package com.example.feature.stats.presentation
The package name is wrong

2020-11-07 07:35 UTC, atabekm requested changes

2020-11-07 07:35 UTC, atabekm commented on app/build.gradle
> +    implementation project(Modules.feature_stats)
Not properly sorted

2020-11-07 07:35 UTC, atabekm commented on buildSrc/src/main/java/Dependencies.kt
> +    const val feature_stats = ":feature-stats"
Same here, not properly sorted

2020-11-07 10:59 UTC, atabekm approved these changes

2020-11-08 11:48 UTC, MaratKhakim approved these changes

2020-11-08 12:00 UTC, merged