added two tabs
shagalalab/qarejet-android pull request #37
Opened 2020-11-09 10:54 UTC by MambetniyazovAmir

2020-11-11 16:59 UTC, Khareken approved these changes

2020-11-11 17:01 UTC, Khareken approved these changes

2020-11-11 23:15 UTC, atabekm commented
Both of you have missed something here. Please pay attention to `Acception criteria` section of the issue before raising or while checking PRs, not everything listed there has been implemented.

2020-11-12 13:55 UTC, atabekm requested changes

2020-11-12 13:55 UTC, atabekm commented on feature-stats/src/main/java/com/shagalalab/feature/stats/presentation/StatsFragment.kt
> +import kotlinx.android.synthetic.main.fragment_stats.*
If you remember, we are not using synthetic imports, but ViewBindings instead.

2020-11-12 13:55 UTC, atabekm commented on feature-stats/src/main/java/com/shagalalab/feature/stats/util/Constants.kt
> +    const val TRANSACTION_TYPE_EXPENSE = 1
Let's keep these constants within the fragment for the time being.

2020-11-12 13:55 UTC, atabekm commented on feature-stats/src/main/res/values/colors.xml
> +    <color name="colorAccent">#03DAC5</color>
Since those are generic colors, they need to be moved to `core-resources`

2020-11-12 13:55 UTC, atabekm commented on feature-stats/src/main/res/values/strings.xml
> +    <string name="expense">expense</string>
Make those to start with capital letters. In tabs, usually they are represented as ALL_CAPS, but as a good practice, it is good to have text in certain order. If for some reason tabs internal implementation is changed in the future, making the text capitalized will make it ready for such changes.

2020-11-14 12:52 UTC, atabekm requested changes

2020-11-14 12:52 UTC, atabekm commented on core-resources/src/main/res/values/colors.xml
> +    <color name="colorAccent">#03DAC5</color>
As I can see, we had these three colors defined in `app` module's colors.xml file. Let's remove it, since `app` has access to `core-resources`, there will be no problems. Also, we have naming inconsistency here, above three use `camelCase`, while below use `snake_case`. As you might remember, we [use](https://github.com/shagalalab/qarejet-android/wiki/Coding-style#resource-files-stringsxml-dimensxml-) snake_case for resource naming.

2020-11-14 12:52 UTC, atabekm commented on core-resources/src/main/res/values/colors.xml
> +    <color name="orange">#FF9800</color>
👍

2020-11-14 12:52 UTC, atabekm commented on feature-stats/build.gradle
> +    implementation project(Modules.core_resources)
Leave a new line below, so that we have a clear separation between local modules and external libraries

2020-11-14 12:52 UTC, atabekm commented on feature-stats/build.gradle
> +        dataBinding true
We are using `viewBinding`, not `dataBinding`

2020-11-14 12:52 UTC, atabekm commented on feature-stats/src/main/res/layout/fragment_stats.xml
> +    </data>
`layout` and `data` is not needed in ViewBinding

2020-11-14 12:52 UTC, atabekm commented on feature-stats/src/main/res/values/colors.xml
> +</resources>
You can remove this file for the moment, if there will be need, you will recreate in the future

2020-11-14 12:52 UTC, atabekm commented on feature-stats/src/main/java/com/shagalalab/feature/stats/presentation/StatsFragment.kt
> +    private lateinit var fragmentStatsBinding: FragmentStatsBinding
To make it shorter, name it just `binding`

2020-11-14 12:52 UTC, atabekm commented on feature-stats/src/main/java/com/shagalalab/feature/stats/presentation/StatsFragment.kt
> +        fragmentStatsBinding.statsTabLayout.addOnTabSelectedListener(object :
In order to not duplicate the same references multiple times, you can group these two lines with:
```
fragmentStatsBinding.statsTabLayout.apply { 
     ...            
}
```

2020-11-14 12:52 UTC, atabekm commented on feature-stats/src/main/res/layout/fragment_stats.xml
> +                android:text="@string/expense" />
Add a new line below

2020-11-15 09:04 UTC, Khareken approved these changes

2020-11-15 09:05 UTC, Khareken approved these changes

2020-11-15 09:08 UTC, Khareken approved these changes

2020-11-15 09:10 UTC, Khareken approved these changes

2020-11-15 09:11 UTC, Khareken approved these changes

2020-11-16 10:03 UTC, atabekm approved these changes

2020-11-16 10:04 UTC, merged